import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,statSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {TelemetryStore,type TelemetryRecord} from '../../../src/observability/telemetry.js';
const base=(id:string):TelemetryRecord=>({requestId:id,startedAt:100,endedAt:110,durationMs:10.5,transport:'chat',model:'test',status:'success',usage:{},groupId:'22'});
test('telemetry persists nullable counts and cache-weighted paired denominator',()=>{const dir=mkdtempSync(join(tmpdir(),'usage-'));try{const path=join(dir,'usage.sqlite');const s=new TelemetryStore(path);s.record({...base('1'),usage:{inputTokens:100,cachedInputTokens:75,outputTokens:5}});s.record({...base('2'),usage:{inputTokens:900}});s.record({...base('3'),status:'error',errorCode:'truncated_response',usage:{inputTokens:100,cachedInputTokens:25}});s.record(base('4'));s.record({...base('1'),usage:{inputTokens:9}});const r=s.summarize({since:0,until:1000});assert.equal(r.requests,4);assert.equal(r.cacheKnownInputTokens,200);assert.equal(r.cacheHitRate,.5);assert.equal(r.missingCacheUsage,2);assert.equal(r.truncatedRequests,1);assert.equal(statSync(path).mode&0o777,0o600);s.close();const again=new TelemetryStore(path);assert.equal(again.summarize({since:0,until:1000,groupId:'23'}).requests,0);again.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('invalid ranges and symlink paths fail closed',()=>{const dir=mkdtempSync(join(tmpdir(),'usage-'));try{const path=join(dir,'usage.sqlite'),s=new TelemetryStore(path);assert.throws(()=>s.summarize({since:-1,until:20}));assert.throws(()=>s.summarize({since:0,until:20,groupId:''}));s.close();symlinkSync(path,join(dir,'link'));assert.throws(()=>new TelemetryStore(join(dir,'link')));}finally{rmSync(dir,{recursive:true,force:true});}});
