/** 按群配置开关的扩展工具。 */
export const EXTENDED_TOOL_NAMES = [
  'get_group_info',
  'get_group_honor',
  'get_group_mutes',
  'read_group_notices',
  'read_group_essence',
  'poke_member',
  'group_sign',
  'set_group_name',
  'set_group_title',
  'set_group_whole_mute',
  'kick_member',
  'set_group_admin',
  'set_group_essence',
  'remove_group_essence',
  'publish_group_notice',
  'delete_group_notice',
  'leave_group',
  'send_group_image',
  'forward_message',
  'send_group_forward',
  'transcribe_voice',
  'create_reminder',
  'list_reminders',
  'update_reminder',
  'cancel_reminder',
  'get_group_ai_voices',
  'send_group_ai_voice',
  'get_group_file_space',
  'list_group_files',
  'read_group_text_file',
  'upload_group_file',
  'create_group_folder',
  'delete_group_file',
  'delete_group_folder',
  'list_group_requests',
  'respond_group_request',
  'list_custom_faces',
  'view_custom_face',
  'send_custom_face',
  'add_custom_face',
  'delete_custom_face',
  'set_custom_face_description',
  'execute_javascript',
  'query_javascript_jobs',
  'cancel_javascript_job',
  'web_search',
  'web_fetch',
  'create_artifact',
  'create_image',
  'list_artifacts',
] as const;

/** 始终提供或由内置模块控制的核心工具（含world工具与格式错误调用的占位名invalid）。 */
export const CORE_TOOL_NAMES = [
  'send_message',
  'finish',
  'get_group_members',
  'get_member_info',
  'read_message',
  'view_images',
  'read_forward',
  'mute_member',
  'unmute_member',
  'recall_message',
  'set_member_card',
  'manage_attention',
  'react_message',
  'get_reaction_users',
  'get_wake_state',
  'get_time',
  'read_events',
  'invalid',
] as const;

/** 日志与遥测承认的全部工具名；不在此列的名字按未知处理。 */
export const ALL_TOOL_NAMES: ReadonlySet<string> = new Set([
  ...EXTENDED_TOOL_NAMES,
  ...CORE_TOOL_NAMES,
  // Retired model tools remain recognizable in historical telemetry.
  'read_messages',
  'ack_events',
]);
